extends Node

## 跨系统事件总线。实体内部优先使用本地信号，系统之间才使用这里。
signal player_state_changed(previous_state: String, next_state: String)
signal weapon_switched(slot_index: int, weapon_data: WeaponData)
signal shot_fired(weapon_data: WeaponData, position: Vector2, direction: Vector2)
signal dash_started(position: Vector2, direction: Vector2)
signal monster_state_changed(monster: Node2D, previous_state: String, next_state: String)
signal monster_alerted(monster: Node2D, source: Vector2)
signal monster_killed(monster: Node2D)
signal noise_emitted(amount: int, position: Vector2, source: Node2D)
signal noise_changed(temporary: float, residual: float)
signal player_health_changed(current: float, maximum: float)
signal player_died()
signal player_parried(attacker: Node2D)
signal consumable_used(item_name: String)
signal boss_awakened(boss: Node2D)
signal run_reset()
signal armor_changed(armor_name: String, durability: int, maximum: int)
signal consumable_changed(item_name: String, count: int, maximum: int)
signal power_node_fixed(node: Node2D, fixed_count: int, total_count: int)
signal map_generated(map_seed: int, level_index: int)
signal extraction_available()
signal run_completed(escaped: bool, kills: int, coins: int)
signal meta_progression_changed(coins: int, skill_points: int)
signal skill_unlocked(skill_name: String)
signal throwable_thrown(throwable_type: int, position: Vector2, direction: Vector2, source: Node2D)
